---
title: "Time Series Analysis"
output: pdf
date: "2024-12-11"
---
```{r}
# loading Packages
library(tidyverse);library(lubridate);library(here)
library(Kendall)
library(zoo)
library(trend)
here()
```

```{r}
# reading in data files 
Elwha_stream <- read.csv(file = 
            here('Final_Project/Data/Processed/Elwa_Stream_Wrangled.csv'), 
            stringsAsFactors = TRUE)
Elwha_stream$Date <- as.Date(Elwha_stream$Date, format = "%Y-%m-%d")
Elwha_sediment <- read.csv(file = 
            here('Final_Project/Data/Processed/Elwa_Sediment_Wrangled.csv'), 
            stringsAsFactors = TRUE)
Elwha_sediment$Date <- as.Date(Elwha_sediment$Date, format = "%Y-%m-%d")


theme1 <- theme_classic(base_size = 14) + 
  theme(axis.text = element_text(color = "darkblue"),
line = element_line(color = "black",
                    linewidth = 2),
legend.position = "right") 
theme_set(theme1)
```

```{r}
# plotting stage height data for each day 

ggplot(Elwha_stream, aes(x = Date, y = Avg_Stage_Height)) + 
  geom_line() + 
  geom_smooth(method = 'lm')

ggplot(Elwha_stream, aes(x = Date, y = Avg_Stage_Height)) + 
  geom_point() + 
  geom_smooth(method = 'lm') + 
  labs( y = 'Mean Daily Stage Height')

Elwha_stream_daily <- Elwha_stream 

Elwha_stream_early <- Elwha_stream_daily %>% 
  filter(Date < as.Date("2017-07-01"))

Stream_daily.ts <- ts(Elwha_stream_early$Avg_Stage_Height, 
                      start = c(2011, 10), frequency = 365)
stream_daily_decomp <- stl(Stream_daily.ts, s.window = 'periodic')
plot(stream_daily_decomp)


SeasonalMannKendall(Stream_daily.ts)
# tau = 0.487, 2-sided pvalue =< 2.22e-16 
# moderate increasing trend 
# can reject the null hypothesis because the P value is less than 0.05. This trend is not random 

##nonseasonal_daily <- Stream_daily.ts -
#stream_daily_decomp$time.series[,"seasonal"] 
#plot(nonseasonal_daily)
#MannKendall(nonseasonal_daily)
```

```{r}
# Averaging by month 
Elwha_stream_monthly <- Elwha_stream %>% 
  mutate(Month = month(Date), Year = year(Date))
Elwha_stream_monthly <- Elwha_stream_monthly %>% 
  group_by(Month, Year) %>% 
  summarise(Avg_Stage_Height = mean(Avg_Stage_Height)) %>% 
  rename(Monthly_Avg_Stage_Height = Avg_Stage_Height)
Elwha_stream_monthly <- mutate(Elwha_stream_monthly, Date = as.Date(
paste(Year, Month, "01", sep = "-")))

ggplot(Elwha_stream_monthly, aes(x = Date, y = Monthly_Avg_Stage_Height)) + 
  geom_line() + 
  geom_smooth(method = 'lm')

ggplot(Elwha_stream_monthly, aes(x = Date, y = Monthly_Avg_Stage_Height)) + 
  geom_point() + 
  geom_smooth(method = 'lm')

stream_monthly.ts <- ts(Elwha_stream_monthly$Monthly_Avg_Stage_Height, start = c(2011, 10), frequency = 12)
stream_monthly_decomp <- stl(stream_monthly.ts, s.window = 'periodic') 
plot(stream_monthly_decomp) 

SeasonalMannKendall(stream_monthly.ts)
# tau = -0.0208 basically no trend 
# p value = 0.87113 cannot reject the null hypothesis indicating no significant trend 

nonseasonal_monthly <- stream_monthly.ts -
stream_monthly_decomp$time.series[,"seasonal"] 
plot(nonseasonal_monthly)

MannKendall(nonseasonal_monthly)
```


```{r}
ggplot(Elwha_sediment, aes(x = Date, y = Discharge)) + 
  geom_line() + 
  geom_smooth(method = 'lm')

ggplot(Elwha_sediment, aes(x = Date, y = Discharge)) + 
  geom_point() + 
  geom_smooth(method = 'lm') + 
  labs(y = 'Discharge (m3/s)')

sediment_daily.ts <- ts(Elwha_sediment$Discharge, start = c(2011, 09), frequency = 365)
sediment_daily_decomp <- stl(sediment_daily.ts, s.window = 'periodic')
plot(sediment_daily_decomp)

SeasonalMannKendall(sediment_daily.ts)
# tau = 1, 2-sided pvalue =< 2.22e-16
# perfectly increasing trend 
# Statistically significant 

```


```{r}
ggplot(Elwha_sediment, aes(x = Date, y = Total_Sed_discharge)) + 
  geom_point() + 
  geom_smooth(method = 'lm')

sediment_discharge.ts <- ts(Elwha_sediment$Total_Sed_discharge, start = c(2011, 09), frequency = 365)
sed_discharge_decomp <- stl(sediment_discharge.ts, s.window = 'periodic')
plot(sed_discharge_decomp)
```
```{r}
SeasonalMannKendall(sediment_discharge.ts)
```

